[background]
path = "/etc/greetd/wallpaper.png"
fit = "Cover"

[GTK]
application_prefer_dark_theme = true
cursor_theme_name = "Bibata-Modern-Ice"
font_name = "JetBrainsMono Nerd Font 11"
icon_theme_name = "Adwaita"
theme_name = "Adwaita"

[commands]
reboot = ["systemctl", "reboot"]
poweroff = ["systemctl", "poweroff"]

[appearance]
greeting_msg = "Welcome back"
