;;; cairn-theme.el --- Generated by cairn's apply-theme.py -*- lexical-binding: t; -*-
;;
;; DO NOT EDIT BY HAND -- regenerated on every `theming/pick-theme.sh` /
;; `apply-theme.py <preset>` run from theming/templates/emacs-theme.el.tmpl.
;; Loaded via cairn-emacs-themer (github.com/skeptomai/cairn-emacs-themer).
;;
;; Ported from omarchy-emacs-themer's 20-emacs.sh face list, adapted to
;; cairn's own palette schema. Two token gaps vs. that schema, resolved
;; here: cairn has no dedicated cursor color (the accent color is used
;; instead) and no split selection foreground/background (the plain
;; foreground color is paired with the single selection color throughout --
;; checked against a real palette where a dedicated pair would have
;; resolved to the same values anyway). See theming/apply-theme.py's
;; emacs_mode_tokens() for the mode-line/LSP-popup color derivation.

(autothemer-deftheme
 cairn "A theme generated from cairn's own palette"
 ((((class color) (min-colors #xFFFFFF)))

   ;; Color palette from the cairn preset
   (bg          "#d8d5cd")
   (fg          "#2e2e2e")
   (cursor-fg   "#d8d5cd")
   (cursor-bg   "#1e66f5")
   (sel-bg      "#1e66f5")
   (black       "#2e2e2e")
   (red         "#d20f39")
   (green       "#40a02b")
   (yellow      "#b85400")
   (blue        "#1e66f5")
   (magenta     "#8839ef")
   (cyan        "#179299")
   (white       "#cccac2")
   (br-black    "#5c5f77")
   (br-red      "#d20f39")
   (br-green    "#40a02b")
   (br-yellow   "#b85400")
   (br-blue     "#1e66f5")
   (br-magenta  "#8839ef")
   (br-cyan     "#179299")
   (br-white    "#d8d5cd")
   )

 ;; Face mappings (aligned with Zed/VSCode/Neovim mappings)
 (
  ;; Core faces
  (default                          (:foreground fg :background bg))
  (cursor                           (:foreground cursor-fg :background cursor-bg))
  (region                           (:foreground fg :background sel-bg))
  (highlight                        (:background sel-bg))
  (shadow                           (:foreground br-black))
  (minibuffer-prompt                (:foreground blue :bold t))
  (link                             (:foreground blue :underline t))
  (link-visited                     (:foreground magenta :underline t))

  ;; Line numbers
  (line-number                      (:foreground br-black))
  (line-number-current-line         (:foreground br-red))

  ;; Search / match
  (isearch                          (:foreground bg :background yellow))
  (lazy-highlight                   (:foreground bg :background br-yellow))
  (match                            (:foreground bg :background blue))

  ;; Syntax highlighting
  (font-lock-keyword-face           (:foreground magenta))
  (font-lock-function-name-face     (:foreground blue))
  (font-lock-function-call-face     (:foreground blue))
  (font-lock-variable-name-face     (:foreground red))
  (font-lock-variable-use-face      (:foreground red))
  (font-lock-string-face            (:foreground green))
  (font-lock-doc-face               (:foreground green :italic t))
  (font-lock-comment-face           (:foreground br-black :italic t))
  (font-lock-comment-delimiter-face (:foreground br-black :italic t))
  (font-lock-constant-face          (:foreground br-red))
  (font-lock-number-face            (:foreground br-red))
  (font-lock-type-face              (:foreground yellow))
  (font-lock-builtin-face           (:foreground cyan))
  (font-lock-preprocessor-face      (:foreground cyan))
  (font-lock-negation-char-face     (:foreground red))
  (font-lock-warning-face           (:foreground yellow :bold t))
  (font-lock-regexp-grouping-construct (:foreground cyan))
  (font-lock-regexp-grouping-backslash (:foreground cyan))

  ;; Mode line — colors computed mode-aware in apply-theme.py
  (mode-line                        (:foreground "#2e2e2e" :background "#1e66f5"))
  (mode-line-inactive               (:foreground "#5c5f77" :background "#d8d5cd"))
  (mode-line-emphasis               (:foreground "#2e2e2e" :bold t))
  (mode-line-buffer-id              (:foreground "#2e2e2e" :bold t))

  ;; Errors / warnings
  (error                            (:foreground red))
  (warning                          (:foreground yellow))
  (success                          (:foreground green))

  ;; Diff / version control
  (diff-added                       (:foreground green))
  (diff-removed                     (:foreground red))
  (diff-changed                     (:foreground magenta))
  (diff-header                      (:foreground blue :bold t))

  ;; Parens
  (show-paren-match                 (:foreground bg :background blue :bold t))
  (show-paren-mismatch              (:foreground bg :background red :bold t))

  ;; Whitespace
  (trailing-whitespace              (:background red))

  ;; Fringe and UI
  (fringe                           (:foreground br-black :background bg))
  (vertical-border                  (:foreground black))

  ;; LSP symbol highlights — use the selection color so all three levels
  ;; feel native. Write highlights get an underline to distinguish them.
  (lsp-face-highlight-textual       (:background sel-bg))
  (lsp-face-highlight-read          (:background sel-bg))
  (lsp-face-highlight-write         (:background sel-bg :underline t))

  ;; LSP UI doc popup — body and header computed mode-aware in apply-theme.py
  (lsp-ui-doc-background            (:foreground "#2e2e2e" :background "#1e66f5"))
  (lsp-ui-doc-header                (:foreground "#d8d5cd" :background "#1e66f5" :bold t))
  (lsp-ui-doc-url                   (:foreground blue :underline t))

 ))

;; Diagnostic underlines are defined outside autothemer-deftheme because
;; autothemer evaluates face specs in a let context where palette names are
;; bound as variables.  The 'wave style symbol has no such binding and would
;; throw "Symbol's value as variable is void: wave".  custom-theme-set-faces
;; takes quoted face specs — pure data — so 'wave is a literal symbol and
;; hex color strings expand naturally from the palette tokens above.
(custom-theme-set-faces 'cairn
  '(flycheck-error   ((t (:underline (:style wave :color "#d20f39")))))
  '(flycheck-warning ((t (:underline (:style wave :color "#b85400")))))
  '(flycheck-info    ((t (:underline (:style wave :color "#179299")))))
  '(flymake-error    ((t (:underline (:style wave :color "#d20f39")))))
  '(flymake-warning  ((t (:underline (:style wave :color "#b85400")))))
  '(flymake-note     ((t (:underline (:style wave :color "#179299"))))))

(provide-theme 'cairn)
